//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P120_UX_Automates.Langues {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P120_UX_Automates.Langues.EN", typeof(EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ticket registered.
        /// </summary>
        internal static string _ticketSave {
            get {
                return ResourceManager.GetString("_ticketSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adult.
        /// </summary>
        internal static string btnAdult {
            get {
                return ResourceManager.GetString("btnAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Airport.
        /// </summary>
        internal static string btnAeroport {
            get {
                return ResourceManager.GetString("btnAeroport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cash.
        /// </summary>
        internal static string btnCash {
            get {
                return ResourceManager.GetString("btnCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Child.
        /// </summary>
        internal static string btnChild {
            get {
                return ResourceManager.GetString("btnChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Credit card.
        /// </summary>
        internal static string btnCreditCard {
            get {
                return ResourceManager.GetString("btnCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment.
        /// </summary>
        internal static string btnGoNext {
            get {
                return ResourceManager.GetString("btnGoNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paris Visit.
        /// </summary>
        internal static string btnParisVisite {
            get {
                return ResourceManager.GetString("btnParisVisite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduced price.
        /// </summary>
        internal static string btnReductPrice {
            get {
                return ResourceManager.GetString("btnReductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Standard.
        /// </summary>
        internal static string btnStandard {
            get {
                return ResourceManager.GetString("btnStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valid tickets.
        /// </summary>
        internal static string btnValid {
            get {
                return ResourceManager.GetString("btnValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1 to 5 days - Adult or Child.
        /// </summary>
        internal static string lbl1a5Jours {
            get {
                return ResourceManager.GetString("lbl1a5Jours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Airport.
        /// </summary>
        internal static string lblAeroport {
            get {
                return ResourceManager.GetString("lblAeroport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à From 18 years.
        /// </summary>
        internal static string lblAgeAdult {
            get {
                return ResourceManager.GetString("lblAgeAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Child, Student.
        /// </summary>
        internal static string lblAgeReduct {
            get {
                return ResourceManager.GetString("lblAgeReduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        internal static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durability.
        /// </summary>
        internal static string lblDurability {
            get {
                return ResourceManager.GetString("lblDurability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à With the phone.
        /// </summary>
        internal static string lblGooglePay {
            get {
                return ResourceManager.GetString("lblGooglePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Métro, Tram, Bus, RER.
        /// </summary>
        internal static string lblMetro {
            get {
                return ResourceManager.GetString("lblMetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paris Visit.
        /// </summary>
        internal static string lblParis {
            get {
                return ResourceManager.GetString("lblParis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proceed to payment!.
        /// </summary>
        internal static string lblProced {
            get {
                return ResourceManager.GetString("lblProced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantity.
        /// </summary>
        internal static string lblQuantity {
            get {
                return ResourceManager.GetString("lblQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are all the desired tickets listed above?.
        /// </summary>
        internal static string lblQuestion {
            get {
                return ResourceManager.GetString("lblQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Summary.
        /// </summary>
        internal static string lblRecap {
            get {
                return ResourceManager.GetString("lblRecap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Order summary.
        /// </summary>
        internal static string lblResumeCommand {
            get {
                return ResourceManager.GetString("lblResumeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Standard.
        /// </summary>
        internal static string lblStandard {
            get {
                return ResourceManager.GetString("lblStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total.
        /// </summary>
        internal static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment methods.
        /// </summary>
        internal static string lblTypeOfPay {
            get {
                return ResourceManager.GetString("lblTypeOfPay", resourceCulture);
            }
        }
    }
}
